[project]
site_name = "Project Kraken"
site_author = "Tristan Nolde"
site_url = "https://trisnol.github.io/project-kraken/"
repo_url = "https://github.com/TrisNol/project-kraken"
repo_name = "TrisNol/project-kraken"
copyright = "&copy; 2025 Tristan Nolde"
dev_addr = "localhost:3000"

[project.theme]
variant = "modern"
logo = "images/logo.png"
favicon = "images/favicon.ico"

[project.theme.icon]
repo = "fontawesome/brands/github"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.extra.consent]
title = "Cookie consent"
description = """
    We use cookies to recognize your repeated visits and preferences, as well
    as to measure the effectiveness of our documentation and whether users
    find what they're searching for. With your consent, you're helping us to
    make our documentation better.
""" 